change release configuration + added validation to build workflow

diff --git a/.github/workflows/build-vsix.yml b/.github/workflows/build-vsix.yml
--- a/.github/workflows/build-vsix.yml
+++ b/.github/workflows/build-vsix.yml
@@ -48,6 +48,33 @@ jobs:
     - name: Build VSIX Project 
       run: msbuild JFrogVSExtension.sln /p:Configuration=Release /p:Platform="Any CPU" /p:BuildInParallel=true /m 
 
+    # Verify that the PDB file is not included in the .vsix file
+    - name: Check for PDB in VSIX
+      run: |
+        $vsixPath = "JFrogVSExtension/bin/Release/JfrogVSExtension.vsix"
+        $pdbExists = $false
+        
+        # Check if the .vsix file contains the PDB file
+        if (Test-Path $vsixPath) {
+            $zipContent = [System.IO.Compression.ZipFile]::OpenRead($vsixPath)
+            foreach ($entry in $zipContent.Entries) {
+                if ($entry.FullName -like "*JfrogVSExtension.pdb") {
+                    $pdbExists = $true
+                    break
+                }
+            }
+            $zipContent.Dispose()
+        } else {
+            Write-Host "VSIX file does not exist."
+        }
+
+        if ($pdbExists) {
+            Write-Host "PDB file exists in VSIX. Please check your project settings."
+            exit 1  # Fail the workflow if the PDB file is found
+        } else {
+            Write-Host "PDB file not found in VSIX. Build is clean."
+        }
+
     # Upload vsix and unit test as artifacts for other workflows usage
     - name: Upload vsix artifacts
       uses: actions/upload-artifact@v3
